/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.10
 * Generated at: 2024-05-12 14:32:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "includes/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "includes/home_navbar.jsp", out, false);
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".carousel-item {\r\n");
      out.write("	height: 100vh;\r\n");
      out.write("	min-height: 300px;\r\n");
      out.write("	background: no-repeat center center scroll;\r\n");
      out.write("	-webkit-background-size: cover;\r\n");
      out.write("	-moz-background-size: cover;\r\n");
      out.write("	-o-background-size: cover;\r\n");
      out.write("	background-size: cover;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<section id=\"service-section\" class=\"mt-5 mb-5 pr-3\">\r\n");
      out.write("	<div class=\"container marketing text-center\">\r\n");
      out.write("\r\n");
      out.write("		<!-- Three columns of text below the carousel -->\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<div class=\"col-lg-4 \">\r\n");
      out.write("				<img class=\"rounded-circle\" src=\"images/party.jpg\"\r\n");
      out.write("					alt=\"Generic placeholder image\" width=\"240\" height=\"240\">\r\n");
      out.write("				<h2>PARTY</h2>\r\n");
      out.write("				<p>The party pulsed with infectious energy, as guests reveled in\r\n");
      out.write("					laughter and music, creating unforgettable memories under a canopy\r\n");
      out.write("					of celebration.</p>\r\n");
      out.write("				\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- /.col-lg-4 -->\r\n");
      out.write("			<div class=\"col-lg-4\">\r\n");
      out.write("				<img class=\"rounded-circle\" src=\"images/sports.jpg\"\r\n");
      out.write("					alt=\"Generic placeholder image\" width=\"240\" height=\"240\">\r\n");
      out.write("				<h2>SPORTS</h2>\r\n");
      out.write("				<p>Sports are the embodiment of determination and teamwork,\r\n");
      out.write("					where athletes strive for excellence and spectators unite in the\r\n");
      out.write("					thrill of competition, forging bonds that transcend boundaries and\r\n");
      out.write("					inspire greatness.</p>\r\n");
      out.write("				\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"col-lg-4\">\r\n");
      out.write("				<img class=\"rounded-circle\" src=\"images/ent.jpg\"\r\n");
      out.write("					alt=\"Generic placeholder image\" width=\"240\" height=\"240\">\r\n");
      out.write("				<h2>ENTERTAINMENT</h2>\r\n");
      out.write("				<p>\r\n");
      out.write("					Entertainment is the spark that ignites our spirits, offering\r\n");
      out.write("					moments of joy and escape from the everyday. It's where dreams\r\n");
      out.write("					dance freely and laughter echoes, uniting hearts in a shared\r\n");
      out.write("					journey of delight.\r\n");
      out.write("					\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<hr class=\"featurette-divider\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"row featurette\">\r\n");
      out.write("	<div class=\"col-md-7\">\r\n");
      out.write("		<div class=\"mt-1 text-center\">\r\n");
      out.write("			<h2 class=\"featurette-heading mt-2\">\r\n");
      out.write("				PARTY\r\n");
      out.write("				<p class=\"text-muted mt-2\">It'll blow your mind.</p>\r\n");
      out.write("			</h2>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"mt-3\">\r\n");
      out.write("			<p class=\"lead\">A lively party filled the air with laughter and\r\n");
      out.write("				music, as friends and family mingled with infectious energy.\r\n");
      out.write("				Colorful decorations adorned the space, adding to the festive\r\n");
      out.write("				atmosphere. Delicious aromas wafted from the buffet table, tempting\r\n");
      out.write("				guests to indulge in culinary delights. From heartfelt conversations\r\n");
      out.write("				to spontaneous dance-offs, the night was alive with unforgettable\r\n");
      out.write("				moments.</p>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"col-md-5\">\r\n");
      out.write("		<img class=\"featurette-image img-fluid mx-auto\" src=\"images/party.jpg\"\r\n");
      out.write("			alt=\"Generic placeholder image\">\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<hr class=\"featurette-divider\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"row featurette\">\r\n");
      out.write("	<div class=\"col-md-7 order-md-2\">\r\n");
      out.write("		<div class=\"mt-1 text-center\">\r\n");
      out.write("			<h2 class=\"featurette-heading mt-2\">\r\n");
      out.write("				SPORTS\r\n");
      out.write("				<p class=\"text-muted mt-2\">Unleashing the Athlete Within: Dive\r\n");
      out.write("					into the World of Sports</p>\r\n");
      out.write("			</h2>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"mt-3\">\r\n");
      out.write("			<p class=\"lead\">Sports ignite the spirit of competition and\r\n");
      out.write("				camaraderie, uniting individuals in pursuit of physical excellence\r\n");
      out.write("				and teamwork. Whether it's the adrenaline rush of a fast-paced game\r\n");
      out.write("				or the solitary focus of individual challenges, sports offer a\r\n");
      out.write("				diverse array of experiences. From the roar of the crowd in stadiums\r\n");
      out.write("				to the quiet intensity of training sessions, athletes push their\r\n");
      out.write("				limits, striving for greatness. Sports transcend boundaries,\r\n");
      out.write("				cultures, and generations, leaving an indelible mark on those who\r\n");
      out.write("				participate and spectate alike.</p>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"col-md-5 order-md-1\">\r\n");
      out.write("		<img class=\"featurette-image img-fluid mx-auto\"\r\n");
      out.write("			src=\"images/sports.jpg\" alt=\"Generic placeholder image\">\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<hr class=\"featurette-divider\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"row featurette\">\r\n");
      out.write("	<div class=\"col-md-7\">\r\n");
      out.write("		<div class=\"mt-1 text-center\">\r\n");
      out.write("			<h2 class=\"featurette-heading mt-2\">\r\n");
      out.write("				ENTERTAINMENT\r\n");
      out.write("				<p class=\"text-muted mt-2\">Entertainment Extravaganza: Delve\r\n");
      out.write("					into the World of Fun and Amusement</p>\r\n");
      out.write("			</h2>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"mt-3\">\r\n");
      out.write("			<p class=\"lead\">Entertainment encompasses a vibrant spectrum of\r\n");
      out.write("				experiences, from captivating performances to immersive storytelling\r\n");
      out.write("				and interactive experiences. It serves as a portal to new worlds,\r\n");
      out.write("				offering moments of joy, wonder, and reflection. Whether through\r\n");
      out.write("				music, theater, film, gaming, or the arts, entertainment captivates\r\n");
      out.write("				audiences, stirring emotions and sparking imagination. It's a realm\r\n");
      out.write("				where creativity knows no bounds, where laughter and excitement\r\n");
      out.write("				reign supreme, leaving lasting impressions and memories to cherish.</p>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"col-md-5\">\r\n");
      out.write("		<img class=\"featurette-image img-fluid mx-auto\" src=\"images/ent.jpg\"\r\n");
      out.write("			alt=\"Generic placeholder image\">\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- footer-section -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "includes/footer.jsp", out, false);
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
